### ISSUE TITLE
Additional rules

### ISSUE THREAD

**Issue by Jean85** [facile-it/facile-coding-standard#13]
I'm scolling through all the rules, searching for anything that we could add for the 0.3 BC release. Here's my suggestions:

 * `array_indentation`: Each element of an array must be indented exactly once.
```diff
<?php
  $foo = [
-   'bar' => [
-    'baz' => true,
-  ],
+    'bar' => [
+        'baz' => true,
+    ],
];
```
 * `class_attributes_separation`: Class, trait and interface elements must be separated with one blank line.
```diff
class Sample
{
  const A = 1;
+
  /** seconds in some hours */
  const B = 3600;
+
  protected function foo()
  {
  }
+
  protected function bar()
  {
  }
-
-
}
```
 * `compact_nullable_typehint`: Remove extra spaces in a nullable typehint. (this will be probably PSR-12 compliant)
```diff
<?php
-function sample(? string $str): ? string
+function sample(?string $str): ?string
```
 * `lowercase_static_reference`: Class static references self, static and parent MUST be in lower case.
 * `method_chaining_indentation`: Method chaining MUST be properly indented. Method chaining with different levels of indentation is not supported.
```diff
$user->setEmail('voff.web@gmail.com')
-         ->setPassword('233434');
+    ->setPassword('233434');
```
 * `multiline_comment_opening_closing`: DocBlocks must start with two asterisks, multiline comments must start with a single asterisk, after the opening slash. Both must end with a single asterisk before the closing slash.
```diff
<?php

-/******
+/*
* Multiline comment with arbitrary asterisks count
- ******/
+ */

-/**\
+/*\
* Multiline comment that seems a DocBlock
*/

/**
* DocBlock with arbitrary asterisk count at the end
- **/
+ */
```
 * `no_blank_lines_after_class_opening`: There should be no empty lines after class opening brace.
```diff
<?php
final class Sample
{
-
    protected function foo()
    {
    }
```

**Comment by Jean85** [comment]
`lowercase_static_reference` cannot be added since it's too new :disappointed: added in 2.12

**Comment by thomasvargiu** [comment]
@Jean85 It's ok IMHO, but I'm not sure about the `method_chaining_indentation` rule.

Should we indent it with 4 spaces or should we align with the first arrow? I think every line should be indendent with 4 spaces.

**Comment by ilario-pierbattista** [comment]
I would limit the usage of `class_attributes_separation` to `["method"]`.
Separating each const or property of the class could make the heading section longer than needed, introducing readability issues.

**Comment by thomasvargiu** [comment]
@ilario-pierbattista 👍  IMHO

**Comment by Jean85** [comment]
@thomasvargiu I agree with the 4 spaces for chaining indentation, otherwise renaming a var would change all the chain in the diff.

@ilario-pierbattista I would agree, but in that respect I prefer separation, also because I use a custom fixer to make all `@var` PHPDocs to a single line. I could port that here, or we could just restrict it to methods only, it's the same for me.
