### ISSUE TITLE
Add risky rules

### ISSUE THREAD

**Issue by Jean85** [facile-it/facile-coding-standard#17]
Since #16, we can now add multiple `RulesProvider`. This means that we can suggest risky rules separately. These are the rules that I think we should use:
 * `dir_constant`: Replaces `dirname(__FILE__)` expression with equivalent `__DIR__` constant.
```diff
-$a = dirname(__FILE__);
+$a = __DIR__;
```
 * `function_to_constant`: Replace core functions calls returning constants with the constants.
```diff
-echo phpversion();
-echo pi();
-echo php_sapi_name();
+echo PHP_VERSION;
+echo M_PI;
+echo PHP_SAPI;
```
 * `is_null`: Replaces `is_null($var)` expression with `null === $var`.
```diff
-$a = is_null($b);
+$a = null === $b;
```
 * `logical_operators`: Use `&&` and `||` logical operators instead of `and` and `or`.
```diff
-if ($a == "foo" and ($b == "bar" or $c == "baz")) {
+if ($a == "foo" && ($b == "bar" || $c == "baz")) {
```
 * `modernize_types_casting`: Replaces intval, floatval, doubleval, strval and boolval function calls with according type casting operator.
```diff
-    $a = intval($b);
-    $a = floatval($b);
-    $a = doubleval($b);
-    $a = strval ($b);
-    $a = boolval($b);
+    $a = (int) $b;
+    $a = (float) $b;
+    $a = (float) $b;
+    $a = (string) $b;
+    $a = (bool) $b;
```
 * `native_constant_invocation`: Add leading `\` before constant invocation of internal constant to speed up resolving. Constant name match is case-sensitive, except for `null`, `false` and `true`.
```diff
-<?php var_dump(PHP_VERSION, M_PI, MY_CUSTOM_PI);
+<?php var_dump(\PHP_VERSION, \M_PI, MY_CUSTOM_PI);
 ```
 * `native_function_invocation`: Add leading `\` before function invocation to speed up function resolving.
```diff
-    return json_encode($options);
+    return \json_encode($options);
```
 * `no_alias_functions`: Master functions shall be used instead of aliases.
```diff
-$a = chop($b);
-close($b);
-$a = doubleval($b);
-$a = fputs($b, $c);
-ini_alter($b, $c);
-$a = is_double($b);
-$a = is_integer($b);
-$a = is_long($b);
-$a = is_real($b);
-$a = is_writeable($b);
-$a = join($glue, $pieces);
-$a = key_exists($key, $array);
-magic_quotes_runtime($new_setting);
-$a = pos($array);
-$a = show_source($filename, true);
-$a = sizeof($b);
-$a = strchr($haystack, $needle);
+$a = rtrim($b);
+closedir($b);
+$a = floatval($b);
+$a = fwrite($b, $c);
+ini_set($b, $c);
+$a = is_float($b);
+$a = is_int($b);
+$a = is_int($b);
+$a = is_float($b);
+$a = is_writable($b);
+$a = implode($glue, $pieces);
+$a = array_key_exists($key, $array);
+set_magic_quotes_runtime($new_setting);
+$a = current($array);
+$a = highlight_file($filename, true);
+$a = count($b);
+$a = strstr($haystack, $needle);
```
 * `non_printable_character`: Remove Zero-width space (ZWSP), Non-breaking space (NBSP) and other invisible unicode symbols.
 * `php_unit_construct`: PHPUnit assertion method calls like `->assertSame(true, $foo)` should be written with dedicated method like `->assertTrue($foo)`.
```diff
-$this->assertEquals(false, $b);
-$this->assertSame(true, $a);
-$this->assertNotEquals(null, $c);
-$this->assertNotSame(null, $d);
+$this->assertFalse($b);
+$this->assertTrue($a);
+$this->assertNotNull($c);
+$this->assertNotNull($d);
```
 * `php_unit_dedicate_assert`: PHPUnit assertions like `assertInternalType`, `assertFileExists`, should be used over `assertTrue`.
```diff
-$this->assertTrue(is_float( $a), "my message");
-$this->assertTrue(is_nan($a));
+$this->assertInternalType('float', $a, "my message");
+$this->assertNan($a);
```
 * `php_unit_mock`: Usages of `->getMock` and `->getMockWithoutInvokingTheOriginalConstructor` methods MUST be replaced by `->createMock` or `->createPartialMock` methods.
```diff
-        $mock = $this->getMockWithoutInvokingTheOriginalConstructor("Foo");
-        $mock1 = $this->getMock("Foo");
-        $mock1 = $this->getMock("Bar", ["aaa"]);
+        $mock = $this->createMock("Foo");
+        $mock1 = $this->createMock("Foo");
+        $mock1 = $this->createPartialMock("Bar", ["aaa"]);
```
 * `php_unit_namespaced`: PHPUnit classes MUST be used in namespaced version, eg `\PHPUnit\Framework\TestCase` instead of `\PHPUnit_Framework_TestCase`.
PHPUnit v6 has finally fully switched to namespaces.
You could start preparing the upgrade by switching from non-namespaced TestCase to namespaced one.
Forward compatibility layer (`\PHPUnit\Framework\TestCase` class) was backported to PHPUnit v4.8.35 and PHPUnit v5.4.0.
Extended forward compatibility layer (`PHPUnit\Framework\Assert`, `PHPUnit\Framework\BaseTestListener`, `PHPUnit\Framework\TestListener` classes) was introduced in v5.7.0.
```diff
-final class MyTest extends \PHPUnit_Framework_TestCase
+final class MyTest extends \PHPUnit\Framework\TestCase
```
 * `php_unit_set_up_tear_down_visibility`: Changes the visibility of the `setUp()` and `tearDown()` functions of PHPUnit to `protected`, to match the PHPUnit TestCase.
```diff
<?php
final class MyTest extends \PHPUnit\Framework\TestCase
{
    private $hello;
-    public function setUp()
+    protected function setUp()
    {
        $this->hello = "hello";
    }
    
-    public function tearDown()
+    protected function tearDown()
    {
        $this->hello = null;
    }
}
```
 * `psr0`: Classes must be in a path that matches their namespace, be at least one namespace deep and the class name should match the file name. **Applying this rule should be risky: This fixer may change your class name, which will break the code that is depended on old name.
```diff
<?php
namespace PhpCsFixer\FIXER\Basic;
-class InvalidName {}
+class Psr0Fixer {}
```
 * `psr4`: Class names should match the file name. This fixer may change your class name, which will break the code that is depended on old name. (diff example same as before)
 * `random_api_migration`: Replaces `rand`, `srand`, `getrandmax` functions calls with their `mt_*` analogs.
```diff
-$a = getrandmax();
-$a = rand($b, $c);
-$a = srand();
+$a = mt_getrandmax();
+$a = mt_rand($b, $c);
+$a = mt_srand();
```
 * `self_accessor`: Inside class or interface element `self` should be preferred to the class name itself.
```diff
<?php
class Sample
{
    const BAZ = 1;
-    const BAR = Sample::BAZ;
+    const BAR = self::BAZ;

    public function getBar()
    {
-        return Sample::BAR;
+        return self::BAR;
    }
}
```

**Comment by thomasvargiu** [comment]
See PR #16

**Comment by thomasvargiu** [comment]
Added in #16
