### ISSUE TITLE
The config writer is not updated for php-cs-fixer 3

### ISSUE THREAD

**Issue by thomasvargiu** [facile-it/facile-coding-standard#40]
The Config Writer [`PhpCsConfigWriter`](https://github.com/facile-it/facile-coding-standard/blob/c095749b39502d3f8d07a6bf5a575d710d568e25/src/Installer/Writer/PhpCsConfigWriter.php) class is not updated for `php-cs-fixer` v3.

ping @Jean85

**Comment by Jean85** [comment]
I don't understand what's wrong.. It seems fine to me.

**Comment by thomasvargiu** [comment]
You're right, it seems fine. I need to look at it better but updating from `v0.4` ti wrote me a different file. I need to reproduce the problem.

**Comment by Jean85** [comment]
Maybe you got the same issue that I fixed in #37?
