### ISSUE TITLE
Improve ruleset provider

### ISSUE THREAD

**Issue by thomasvargiu** [facile-it/facile-coding-standard#5]
We should find a way to improve ruleset provider.

Someone would like to implement other rulesets, like risky ruleset or phpdoc rulesets.
Would be better to standardize these rulesets too.

The idea is a RulesetProvider builder or something like that.

**Comment by thomasvargiu** [comment]
Could we add some `RuleProvider` interface with a default implementation?
When someone want to change the default implementation they are free to implement a custom implementation, maybe merging rules with PHP functions or with some external utility for recursive merging, decorating the default `RuleProvider`. Could be a good idea?

**Comment by Jean85** [comment]
I think an interface may be an overkill here, since we cannot hook it directly to PHPCSFixer, we have to go throw a raw array anyway. The `array_merge` has to be done anyway...

Maybe a simple `getRiskyRules()`?

**Comment by thomasvargiu** [comment]
Implemented in #16
